version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    networks:
      - jenkins-network

  webapi:
    build: .
    container_name: la-container
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    networks:
      - jenkins-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDatabase;User Id=sa;Password=YourPassword123;

  angularapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-container
    ports:
      - "4200:80"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
